# vim:ft=ansible:
---

- name: configure journald
  template:
    src: journald.conf.j2
    dest: "{{ journald_systemd_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart journald
