# vim:ft=ansible:
---

- include_vars: "{{ ansible_os_family|lower }}.yml"

- name: configure logrotate
  template:
    src: "{{ ansible_os_family|lower }}/logrotate.conf.j2"
    dest: "{{ logrotate_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify: restart logrotate
